# WRITE CI/CD WORKFLOW FOR CLIENT HERE WHEN THERE IS MAIN BRANCH CODE WILL DEPLOY  fro REACT TSX VITE
name: Client CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to production server
        run: |
          echo "Deploying to production server..."
          # Add your deployment commands here, e.g., rsync, scp, etc.
          # Example:
          # rsync -avz --delete dist/

